services:
- type: web
  name: career-competency-tracker
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn wsgi:app
  plan: free
  envVars:
    - key: FLASK_APP
      value: wsgi.py
    - key: ENV
      value: production
    - key: PYTHONPATH
      value: .
  autoDeploy: true

envVarGroups:
- name: flask-postgres-api-settings
  envVars:
  - key: ENV
    value: production
  - key: FLASK_APP
    value: wsgi.py
    

databases:
- name: flask-postgres-api-db
  plan: free
  databaseName: mydb